version: '3.8'

services:
  kerberos_flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/kerberos-auth-flask.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kerberos_flask_app
